### ISSUE TITLE
Support loading ONNX models directly

### ISSUE THREAD

**Issue by robertknight** [robertknight/rten#141]
ONNX models currently have to be converted into the FlatBuffers-based `.rten` format to use them.

The `.rten` format is intended to support efficient loading, and have a small code footprint (it serves a similar role to [ORT](https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html)). However the need to convert models is a barrier to using this library, and inconvenient in projects that want to trial or mix different runtimes for various reasons. It would reduce friction if `.onnx` models could be loaded directly.

**Sub-tasks:**

- [x] Implement ONNX model deserialization (https://github.com/robertknight/rten/pull/954)
- [x] Implement file type detection for `Model::load_*` methods (https://github.com/robertknight/rten/pull/961)
- [x] Support loading ONNX models with embedded weights (https://github.com/robertknight/rten/pull/958)
- [x] Support loading ONNX models with external weights (https://github.com/robertknight/rten/pull/963)
- [x] Support loading ONNX models with memory mapping (https://github.com/robertknight/rten/pull/964)
- [x] Support promotion of attributes to inputs for older ONNX models (see `generate_input_from_attr` uses in rten-convert) (https://github.com/robertknight/rten/pull/966)
- [x] ~~Support loading ONNX models with f16 weights via f16 -> f32 conversion at model load time~~ (_Deferred to later release_)
- [x] Test all the examples in rten-examples using ONNX versions of the models
- [x] Update documentation for rten crate to include ONNX model support (https://github.com/robertknight/rten/pull/969)
- [x] Update project README to mention ONNX model support (https://github.com/robertknight/rten/pull/970)
- [x] Update documentation for examples to skip ONNX -> rten format conversion step where possible (https://github.com/robertknight/rten/pull/968)
- [x] Review `rten_convert/converter.py` to see if there is any remaining logic which needs to be re-implemented for ONNX format support (https://github.com/robertknight/rten/pull/989)
- [x] Decide how to handle bool and i64 input and output tensors in MVP. This might mean simply documenting the fact that the inputs/outputs should use i32 tensors instead. (https://github.com/robertknight/rten/pull/1002)
- [x] Document the differences between the rten and ONNX formats and when to choose each (https://github.com/robertknight/rten/pull/1003)
- [x] Add crate features to control which formats are enabled (https://github.com/robertknight/rten/pull/1004)
- [x] Publish new releases of rten crate and CLI which support ONNX 🚢

**Comment by robertknight** [comment]
Had a look at Rust protocol buffers runtimes:

- [Prost](https://github.com/tokio-rs/prost) has the widest adoption, but it has downsides:
  - It allocates `Vec<T>s` for each repeated field, with an exception for bytes (https://github.com/tokio-rs/prost/pull/449)
  - It requires protoc installed at build time if you follow their recommended steps to compile protos as part of a `build.rs`
- [quick-protobuf](https://github.com/tafia/quick-protobuf) has less adoption and hasn't been released in a while, but seems much more aligned with this project's priorities:
  - Minimizes allocations when deserializing
  - Does not require protoc installed

**Comment by robertknight** [comment]
Support for loading ONNX models directly has been released as part of RTen v0.23!
