### ISSUE TITLE
Implement `If` operator

### ISSUE THREAD

**Issue by robertknight** [robertknight/rten#308]
[`If`](https://onnx.ai/onnx/operators/onnx__If.html) is the most widely used of the ONNX control flow operators. Implementing this will involve adding the infrastructure to support executing subgraphs.

**Subtasks:**

- [x] Make input IDs, output IDs and node name -> ID lookup part of the `Graph` type (https://github.com/robertknight/rten/pull/309)
- [x] Add initial implementation of `If` operator (https://github.com/robertknight/rten/pull/306)
- [x] Share tensor pool between parent graph and subgraphs (https://github.com/robertknight/rten/pull/312)
- [x] Propagate graph run options from parent graph to subgraphs (https://github.com/robertknight/rten/pull/311)
- [x] Take into account dependencies due to captured values when planning graph execution (https://github.com/robertknight/rten/pull/317)
  - Constant propagation should retain values that are needed as captures
  - When computing an operator's input dependencies, captured values of that operator's subgraphs should be included
- [x] Apply graph optimizations to subgraphs (already handled in https://github.com/robertknight/rten/pull/306)
- [x] Make total param count reported by rten-cli include subgraphs (https://github.com/robertknight/rten/pull/319)
- [x] Convert captured values that are constants in the parent graph into constants in the subgraph (https://github.com/robertknight/rten/pull/320)
  - This is necessary for certain optimizations to work in the subgraph, if the optimization requires a particular node to be constant
  - This should avoid duplicating the weights
